### ISSUE TITLE
Disruption information on mobile 

### ISSUE THREAD

**Issue by RachelFoy** [wmcadigital/wmn-disruptions#413]
When looking at map view on mobile, if there is an incident, when you click it the test is down below the search information. It is unclear that you need to scroll down. Even on web as the text is big it can be misleading. Can the incident information be a pop up next to the icon? 

Video example of mobile: https://wmcanet-my.sharepoint.com/:v:/g/personal/rachel_foy_tfwm_org_uk/ESCo8-q7J5JOpuWy1cFYfgUBl-DR3elPcfECnN1WJHQ5GA?e=HJ0s47

**Comment by KaterinaKir** [comment]
@RachelFoy  Unfortunately, the pop up is not accessible interface element and it would have to large to put all information therefore we decided to use the same approach as Google maps where we display information on the left. Users are familiar with this pattern because it is widely used (google). What we can do on mobile is to tag disruption info so when user clicks on the disruption indicator, it will take them straight to disruption message without the need to scroll.

**Comment by RachelFoy** [comment]
Can this happen on desktop too? With the size of the font for the search is can be pretty far down the screen, would be good to auto scroll to it for both

**Comment by KaterinaKir** [comment]
Yes, I think we can implement this on desktop as well.
